/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerEngenharia;
import controller.ControllerEventosSistema;
import controller.ControllerParadasMaquina;
import controller.ControllerProducao;
import controller.ControllerReservaPesagem;
import controller.LogErro;
import controller.Login;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.ComposicaoCobre;
import model.Engenharia;
import model.Maquina;
import model.Paradas;
import model.ParadasMaquina;
import model.Producao;
import model.ProdutoCarretel;
import model.ProdutoMaquina;
import model.ProgramacaoMaquina;
import model.ReservaPesagem;
import model.Usuario;

/**
 *
 * @author renato.soares
 */
public class JFApontamentoProducao extends javax.swing.JFrame {
    private Login login = new Login();
    private Maquina maquina = new Maquina();
    private ProdutoCarretel prodCar = new ProdutoCarretel();
    private Producao prod = new Producao();
    private final LogErro erro = new LogErro();
    private ProgramacaoMaquina prog = new ProgramacaoMaquina();
    private ParadasMaquina paradasProcesso;
    private List<Paradas> preParadas = null;
    private List<Usuario> usr = new ArrayList<>();
    private List<ComposicaoCobre> compCobre = new ArrayList<>();
    private List<ReservaPesagem> reservaPesagem = new ArrayList<>();
    private int perdaEstimada=0;
    private JTable preParadasApontadas;
    /**
     * Creates new form JFApontamentoProducao
     * @param maquina
     * @param login
     * @param prodmaq
     * @param prodCar
     * @param prod
     * @param prog
     */
    public JFApontamentoProducao(Maquina maquina, Login login,ProdutoMaquina prodmaq,
            ProdutoCarretel prodCar,Producao prod,ProgramacaoMaquina prog, JTable preParadas) {
        initComponents();
        this.login = login;
        this.maquina = maquina;
        this.prodCar = prodCar;
        this.prod = prod;
        this.prog = prog;
        this.preParadasApontadas=preParadas;
        setarDadosProducao(); 
        buscarParadasProcessoProducao();
        buscaDadosConsumoMp();
        buscaHistoricoOperadores();
        calcularPerdaProcessual();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelRoot = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMaquina = new javax.swing.JPanel();
        jLabelCodMaquina = new javax.swing.JLabel();
        jLabelMaquina = new javax.swing.JLabel();
        jPanelItemProduzido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelCodItem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelLote = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelMetragem = new javax.swing.JLabel();
        jPanelCarretelSaida = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabelCodEmb = new javax.swing.JLabel();
        jLabelDescEmbalagem = new javax.swing.JLabel();
        jPanelParadas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableParadas = new javax.swing.JTable();
        jPanelMateriaPrima = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableConsumoMP = new javax.swing.JTable();
        jPanelObservacoes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanelAcoes = new javax.swing.JPanel();
        jButtonApontar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableHistoricoOperador = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conferência de Produção");
        setSize(new java.awt.Dimension(1000, 850));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(902, 800));
        jScrollPane1.setRequestFocusEnabled(false);

        jPanelRoot.setPreferredSize(new java.awt.Dimension(900, 900));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conferência de Apontamento");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelMaquina.setBorder(javax.swing.BorderFactory.createTitledBorder("Maquina:"));
        jPanelMaquina.setPreferredSize(new java.awt.Dimension(150, 44));

        jLabelCodMaquina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodMaquina.setText("jLabelCodMaquina");

        jLabelMaquina.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelMaquina.setText("jLabelMaquina");

        javax.swing.GroupLayout jPanelMaquinaLayout = new javax.swing.GroupLayout(jPanelMaquina);
        jPanelMaquina.setLayout(jPanelMaquinaLayout);
        jPanelMaquinaLayout.setHorizontalGroup(
            jPanelMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCodMaquina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMaquina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMaquinaLayout.setVerticalGroup(
            jPanelMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaquinaLayout.createSequentialGroup()
                .addGroup(jPanelMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodMaquina)
                    .addComponent(jLabelMaquina))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanelItemProduzido.setBorder(javax.swing.BorderFactory.createTitledBorder("Item produzido:"));

        jLabel2.setText("Cod. Item:");

        jLabelCodItem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCodItem.setText("400503240100");

        jLabel3.setText("Descrição:");

        jLabelDescricao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDescricao.setText("jLabelDescricao");

        jLabel4.setText("Lote:");

        jLabelLote.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLote.setText("jLabelLote");

        jLabel6.setText("Metragem:");

        jLabelMetragem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMetragem.setText("jLabelMetragem");

        javax.swing.GroupLayout jPanelItemProduzidoLayout = new javax.swing.GroupLayout(jPanelItemProduzido);
        jPanelItemProduzido.setLayout(jPanelItemProduzidoLayout);
        jPanelItemProduzidoLayout.setHorizontalGroup(
            jPanelItemProduzidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemProduzidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelItemProduzidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItemProduzidoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMetragem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelItemProduzidoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCodItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelItemProduzidoLayout.setVerticalGroup(
            jPanelItemProduzidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemProduzidoLayout.createSequentialGroup()
                .addGroup(jPanelItemProduzidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelCodItem)
                    .addComponent(jLabel3)
                    .addComponent(jLabelDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItemProduzidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelLote)
                    .addComponent(jLabel6)
                    .addComponent(jLabelMetragem)))
        );

        jPanelCarretelSaida.setBorder(javax.swing.BorderFactory.createTitledBorder("Carretel de saida:"));

        jLabel9.setText("Embalagem:");

        jLabelCodEmb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCodEmb.setText("jLabelCodEmb");

        jLabelDescEmbalagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelDescEmbalagem.setText("jLabelDescEmbalagem");

        javax.swing.GroupLayout jPanelCarretelSaidaLayout = new javax.swing.GroupLayout(jPanelCarretelSaida);
        jPanelCarretelSaida.setLayout(jPanelCarretelSaidaLayout);
        jPanelCarretelSaidaLayout.setHorizontalGroup(
            jPanelCarretelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarretelSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCodEmb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescEmbalagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCarretelSaidaLayout.setVerticalGroup(
            jPanelCarretelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCarretelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(jLabelCodEmb)
                .addComponent(jLabelDescEmbalagem))
        );

        jPanelParadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Paradas:"));

        jTableParadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seq.", "cod. Parada", "Descrição", "Observação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableParadas);

        javax.swing.GroupLayout jPanelParadasLayout = new javax.swing.GroupLayout(jPanelParadas);
        jPanelParadas.setLayout(jPanelParadasLayout);
        jPanelParadasLayout.setHorizontalGroup(
            jPanelParadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelParadasLayout.setVerticalGroup(
            jPanelParadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanelMateriaPrima.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumo de matéria prima:"));

        jTableConsumoMP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seq.", "Item ", "Descrição", "Lote", "Embalagem", "Num. Pes.", "Quantidade", "Unidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableConsumoMP);

        javax.swing.GroupLayout jPanelMateriaPrimaLayout = new javax.swing.GroupLayout(jPanelMateriaPrima);
        jPanelMateriaPrima.setLayout(jPanelMateriaPrimaLayout);
        jPanelMateriaPrimaLayout.setHorizontalGroup(
            jPanelMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriaPrimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanelMateriaPrimaLayout.setVerticalGroup(
            jPanelMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelObservacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações"));

        jScrollPane4.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanelObservacoesLayout = new javax.swing.GroupLayout(jPanelObservacoes);
        jPanelObservacoes.setLayout(jPanelObservacoesLayout);
        jPanelObservacoesLayout.setHorizontalGroup(
            jPanelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelObservacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanelObservacoesLayout.setVerticalGroup(
            jPanelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações:"));

        jButtonApontar.setText("Realizar Apontamento");
        jButtonApontar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApontarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcoesLayout = new javax.swing.GroupLayout(jPanelAcoes);
        jPanelAcoes.setLayout(jPanelAcoesLayout);
        jPanelAcoesLayout.setHorizontalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButtonApontar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAcoesLayout.setVerticalGroup(
            jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLayout.createSequentialGroup()
                .addGroup(jPanelAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApontar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Operadores:"));

        jTableHistoricoOperador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "Nome", "Data e hora", "Encarregado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHistoricoOperador.setColumnSelectionAllowed(true);
        jScrollPane6.setViewportView(jTableHistoricoOperador);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelRootLayout = new javax.swing.GroupLayout(jPanelRoot);
        jPanelRoot.setLayout(jPanelRootLayout);
        jPanelRootLayout.setHorizontalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMaquina, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addComponent(jPanelItemProduzido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCarretelSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelParadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMateriaPrima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelObservacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelRootLayout.setVerticalGroup(
            jPanelRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelItemProduzido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCarretelSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanelRoot);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonApontarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApontarActionPerformed
        // TODO add your handling code here:
        ControllerProducao ctr = new ControllerProducao();
        if(ctr.registrarApontamentoPesagem(prod, perdaEstimada, usr, maquina, prog, jTextPane1.getText(),
                reservaPesagem,paradasProcesso,compCobre,login)){
            JOptionPane.showMessageDialog(rootPane,"Registro de apontamento realizado com sucesso!","Registro de produção",JOptionPane.INFORMATION_MESSAGE);
            
            ControllerEventosSistema ctrEvt = new ControllerEventosSistema();
            if(!ctrEvt.verificaPreApontamento("1" ,maquina.getCodigo(),"",true,0,0)){
                JOptionPane.showMessageDialog(rootPane,"Falha ao registrar motivo da parada, por favor indique manualmentente","Registro de motivo de parada",JOptionPane.ERROR_MESSAGE);
            }else{
                verificarMotivosPreApontados();
            }        
            FecharJanelaApontamento(true);            
        }else{
            JOptionPane.showMessageDialog(rootPane,"Falha ao realizar o registro de apontamento de produção \n "
                    + "por favor tente novamente!","Registro de produção",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_jButtonApontarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        FecharJanelaApontamento(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        FecharJanelaApontamento(false);
    }//GEN-LAST:event_formWindowClosing
        
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApontar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodEmb;
    private javax.swing.JLabel jLabelCodItem;
    private javax.swing.JLabel jLabelCodMaquina;
    private javax.swing.JLabel jLabelDescEmbalagem;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelLote;
    private javax.swing.JLabel jLabelMaquina;
    private javax.swing.JLabel jLabelMetragem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAcoes;
    private javax.swing.JPanel jPanelCarretelSaida;
    private javax.swing.JPanel jPanelItemProduzido;
    private javax.swing.JPanel jPanelMaquina;
    private javax.swing.JPanel jPanelMateriaPrima;
    private javax.swing.JPanel jPanelObservacoes;
    private javax.swing.JPanel jPanelParadas;
    private javax.swing.JPanel jPanelRoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTableConsumoMP;
    private javax.swing.JTable jTableHistoricoOperador;
    private javax.swing.JTable jTableParadas;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void setarDadosProducao() {
        try {
            jLabelCodMaquina.setText(this.maquina.getCodigo());
            jLabelMaquina.setText(this.maquina.getDescricao());
            jLabelCodItem.setText(this.prog.getProduto().getCodigo());
            jLabelDescricao.setText(this.prog.getProduto().getDescricao());
            jLabelLote.setText(this.prog.getLoteproducao());
            jLabelMetragem.setText(String.valueOf(this.prod.getMetragemProduzida()));
            jLabelCodEmb.setText(prodCar.getCarretel().getCodigo());
            jLabelDescEmbalagem.setText(prodCar.getCarretel().getDescricao());                        
        } catch (Exception e) {
            e.printStackTrace();
            erro.gravaErro(e);
        }
    }
    
    private void buscarParadasProcessoProducao() {
        try {
            int linha = 0;
            ControllerParadasMaquina paradas = new ControllerParadasMaquina(this.maquina.getCodigo());
            DefaultTableModel table = (DefaultTableModel) jTableParadas.getModel();            
            this.paradasProcesso = paradas.buscaParadasProcessoAtual(this.maquina.getCodigo());
            for (int i=0;i<this.paradasProcesso.getListaParadas().size();i++){
                linha ++;
                String obs ="";
                if(this.paradasProcesso.getListaParadas().get(i).getCodPesagemSaida()!=0){
                    obs = String.valueOf(this.paradasProcesso.getListaParadas().get(i).getCodPesagemSaida());
                }
                if(paradasProcesso.getListaParadas().get(i).getObservacao()!=null){
                    if(!paradasProcesso.getListaParadas().get(i).getObservacao().trim().equals("")){
                        if(obs.trim().equals("")){
                            obs = this.paradasProcesso.getListaParadas().get(i).getObservacao();
                        }else{
                            obs = obs + " - " + this.paradasProcesso.getListaParadas().get(i).getObservacao();
                        }
                    }
                }
                table.addRow(new Object[]{String.valueOf(linha),this.paradasProcesso.getListaParadas().get(i).getCodigo(),
                    this.paradasProcesso.getListaParadas().get(i).getAbreviacao(), 
                    obs});
                
            }
            ControllerEventosSistema ctr = new ControllerEventosSistema();
            preParadas = ctr.BuscaPreApontamentos(this.maquina.getCodigo());
            for (int i=0;i<preParadas.size();i++){ 
                linha ++;
                    table.addRow(new Object[]{String.valueOf(linha),preParadas.get(i).getCodigo()
                            ,preParadas.get(i).getAbreviacao(),preParadas.get(i).getObservacao()});                    
                }
        } catch (Exception e) {
            e.printStackTrace();
            erro.gravaErro(e);
        }
    }
    
    private void buscaDadosConsumoMp(){
        try {
            List<Engenharia> engenharia=null;
            ControllerEngenharia ctr = new ControllerEngenharia();
            engenharia=ctr.buscaListaEngenhariaEmProducao(this.prog.getProduto().getCodigo(), 
                    this.maquina.getCodigo(),this.prod.getMetragemProduzida());
            
            for (int i=0;i<engenharia.size();i++){                                                              
                ReservaPesagem res = new ReservaPesagem();
                //res.setSequencia(linha);
                res.setCodigoPesagem(prog.getLoteproducao() + prod.getCarretelSaida()+"0");
                res.setItemReserva(engenharia.get(i).getCodItem());
                res.setLoteReserva(engenharia.get(i).getLote());
                res.setItemDescricao(engenharia.get(i).getDescricao());
                res.setQtosfios(0);
                res.setCodigoEmbalagem("");
                res.setQuantidade(engenharia.get(i).getQuantidade()*prod.getMetragemProduzida());
                res.setCodigoEmbalagelTroca("");
                res.setLoteReservaTroca("");
                res.setIdMatPrima(0); 
                res.setUnidade("Kilos");
                this.reservaPesagem.add(res);
            }
            ControllerReservaPesagem resPes = new ControllerReservaPesagem();
            this.reservaPesagem = resPes.buscaConsumoCobreProducaoAtual(this.reservaPesagem, this.maquina.getCodigo());
            DefaultTableModel table = (DefaultTableModel) jTableConsumoMP.getModel();
            for (int i=0;i<this.reservaPesagem.size();i++){
                table.addRow(new Object[]{String.valueOf(i+1),this.reservaPesagem.get(i).getItemReserva(),
                    this.reservaPesagem.get(i).getItemDescricao(),this.reservaPesagem.get(i).getLoteReserva(),
                    this.reservaPesagem.get(i).getCodigoEmbalagem(),this.reservaPesagem.get(i).getIdMatPrima(),
                    this.reservaPesagem.get(i).getQuantidade(),this.reservaPesagem.get(i).getUnidade()});       
            }
            ControllerProducao ctrProd = new ControllerProducao();            
            compCobre = ctrProd.montaComposicaoCobre(reservaPesagem,(int)prod.getMetragemProduzida(),prog.getQtdFiosEntrada());
            
        } catch (Exception e) {
            e.printStackTrace();
            erro.gravaErro(e);
        }
    }

    private void buscaHistoricoOperadores() {
        try {
            
            ControllerEventosSistema ctr = new ControllerEventosSistema();
            this.usr=ctr.buscaListaEventosUsuarioLogin(prod.getLoteProducao());
            if(this.usr!=null){
                DefaultTableModel table = (DefaultTableModel) jTableHistoricoOperador.getModel();
                if(this.usr.size()>0){                                        
                     for (int i=0;i<this.usr.size();i++){
                        table.addRow(new Object[]{this.usr.get(i).getCodigoOperador(),this.usr.get(i).getNome(),
                            this.usr.get(i).getDataHoraLogin(),this.usr.get(i).getNomeEncarregado() });
                     }
                }else{
                    this.usr.add(login);
                    table.addRow(new Object[]{this.usr.get(0).getCodigoOperador(),this.usr.get(0).getNome(),
                            this.usr.get(0).getDataHoraLogin(),this.usr.get(0).getNomeEncarregado()});
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            erro.gravaErro(e);
        }
    }

    private void calcularPerdaProcessual() {
        if(!prod.getItemProducao().substring(0,3).equals("4001")){
            ControllerProducao ctr = new ControllerProducao();
            if(prod.getItemProducao().substring(0,3).equals("4002")){
                this.perdaEstimada = ctr.buscaFatorPerdaItem(prod.getItemProducao());
            }else{
                if(ctr.verificaItemAlongamento(prod.getItemProducao())){
                    this.perdaEstimada = 0;
                }else{
                    this.perdaEstimada = ctr.buscaPerdaEstimadaMateriaPrima(reservaPesagem);
                }
            }
        }
    }    
    
    private void verificarMotivosPreApontados() {
        List<Paradas> preParadas = null;
        try {
            ControllerEventosSistema ctr = new ControllerEventosSistema();
            preParadas = ctr.BuscaPreApontamentos(maquina.getCodigo());            
            if(preParadas!=null){
                DefaultTableModel modelo = (DefaultTableModel)preParadasApontadas.getModel();
                for (int i=0;i<preParadas.size();i++){   
                    modelo.addRow(new Object[]{preParadas.get(i).getCodigo(),preParadas.get(i).getAbreviacao()
                            ,preParadas.get(i).getDescricao(),preParadas.get(i).getObservacao()});                    
                }                
            }
        } catch (NumberFormatException e) {
            erro.gravaErro(e);
        }
    }

    private void FecharJanelaApontamento(boolean b) {
        if(b){            
            JFPrincipal.ZerarMetragemCarretelSaida();            
        }
        dispose();
    }
}
