/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LogErro;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author renato.soares
 */
public class CanvasBigBag extends javax.swing.JPanel {
    LogErro erro = new LogErro();
    BufferedImage carretel;
    /**
     * Creates new form CanvasBigBag
     */
    public CanvasBigBag() {
        initComponents();
         try {
            this.carretel = ImageIO.read(getClass().getResource("/images/Bigbag.png"));
        } catch (IOException ex) {
            ex.printStackTrace();
            erro.gravaErro(ex);
        }
    }
    @Override
    protected  void paintComponent(Graphics g){
        try {                    
            super.paintComponent(g);
            g.drawImage(carretel.getScaledInstance(this.getWidth(),this.getHeight(), 0), 0, 0, null);
        } catch (Exception e) {
            erro.gravaErro(e);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
