/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerEngenhariaAlternativa;
import controller.ControllerReservaMaquina;
import controller.ControllerUtil;
import dao.PesagemDAO;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import model.Pesagem;
import model.Produto;

/**
 *
 * @author renato.soares
 */
public class JFDTrocaCarretelEntrada extends javax.swing.JDialog {    
    List<Produto> prods = new ArrayList<>();
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private Pesagem pesSaida;
    private int metragem;
    private String codMaquina;
    private String lote;
    private boolean montagem=false;

        
    public void setMontagem(boolean montagem) {
        this.montagem = montagem;
    }
            
    public Pesagem getPesSaida() {
        return pesSaida;
    }

    public Pesagem getPesEntrada() {
        return pesEntrada;
    }
    private Pesagem pesEntrada;

    public void setMetragem(int metragem) {
        this.metragem = metragem;
    }

    public void setCodMaquina(String codMaquina) {
        this.codMaquina = codMaquina;
    }

    public void setLote(String lote) {
        this.lote = lote;
    }
    /**
     * Creates new form JFDTrocaCarretelEntrada
     * @param parent
     * @param modal
     */
    public JFDTrocaCarretelEntrada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        limparCampos();
        jTFNumeroPesagem.requestFocus();
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCodItemSaida = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDescSaida = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelNumFiosSaida = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTFNumeroPesagemSaida = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabelBobFuSaida = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelLoteSaida = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEngAlternativa = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFNumeroPesagem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabelBobFu = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelLote = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelCodItemEntrada = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelDescEntrada = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelNumFiosEntrada = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Troca de Carretel de Entrada");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.red);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Troca de Carretel de entrada", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("Item utilizado na entrada");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Codigo:");

        jLabelCodItemSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodItemSaida.setText("jLabelCodItemSaida");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Descrição:");

        jLabelDescSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDescSaida.setText("jLabelDescSaida");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Item para ser trocado (SAÍDA) :");

        jLabel14.setText("Numero de fios:");

        jLabelNumFiosSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNumFiosSaida.setText("000");

        jLabel16.setText("Numero da pesagem: ");

        jTFNumeroPesagemSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFNumeroPesagemSaida.setText("000000");
        jTFNumeroPesagemSaida.setToolTipText("");
        jTFNumeroPesagemSaida.setEnabled(false);

        jLabel17.setText("Bobina / Fuster: ");

        jLabelBobFuSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBobFuSaida.setText("0000000");

        jLabel18.setText("Lote:");

        jLabelLoteSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLoteSaida.setText("000000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(2, 2, 2)
                                .addComponent(jLabelCodItemSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFNumeroPesagemSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelBobFuSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLoteSaida)
                            .addComponent(jLabelNumFiosSaida)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDescSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTFNumeroPesagemSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelBobFuSaida)
                    .addComponent(jLabel18)
                    .addComponent(jLabelLoteSaida))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumFiosSaida)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabelCodItemSaida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelDescSaida))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("Exibe os itens da engenharia alternativa.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Alternativas:");

        jTableEngAlternativa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEngAlternativa.setToolTipText("Itens que podem ser utilizados para a produção atual.");
        jScrollPane2.setViewportView(jTableEngAlternativa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setToolTipText("Item montado na maquina.");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Item escolhido para ser montado (ENTRADA) :");

        jLabel9.setText("Numero da pesagem: ");

        jTFNumeroPesagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFNumeroPesagem.setText("000000");
        jTFNumeroPesagem.setToolTipText("Digite o numero da pesagem do carretel de entrada.");
        jTFNumeroPesagem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNumeroPesagemFocusLost(evt);
            }
        });
        jTFNumeroPesagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNumeroPesagemKeyPressed(evt);
            }
        });

        jLabel10.setText("Bobina / Fuster: ");

        jLabelBobFu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelBobFu.setText("0000000");

        jLabel11.setText("Lote:");

        jLabelLote.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLote.setText("000000");

        jLabel12.setText("Codgo Item:");

        jLabelCodItemEntrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodItemEntrada.setText("jLabelCodItemEntrada");

        jLabel13.setText("Descrição:");

        jLabelDescEntrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDescEntrada.setText("jLabelDescEntrada");

        jLabel15.setText("Numero de fios:");

        jLabelNumFiosEntrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNumFiosEntrada.setText("000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDescEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCodItemEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNumeroPesagem, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelBobFu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLote)
                            .addComponent(jLabelNumFiosEntrada))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTFNumeroPesagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelBobFu)
                    .addComponent(jLabel11)
                    .addComponent(jLabelLote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabelCodItemEntrada)
                    .addComponent(jLabel15)
                    .addComponent(jLabelNumFiosEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabelDescEntrada))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.setEnabled(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton)))
        );

        getRootPane().setDefaultButton(okButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        if(montagem){
            doClose(RET_OK);
        }else{
            ControllerReservaMaquina ctr = new ControllerReservaMaquina();
            if(ctr.trocaCarrtelEntrada(pesSaida, pesEntrada)){
                doClose(RET_OK);        
            }else{
                JOptionPane.showMessageDialog(rootPane,"Falha ao registrar troca do carretel de entrada \n "
                        + "Por favor tente novamente.","Troca do carretel de entrada",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jTFNumeroPesagemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNumeroPesagemFocusLost
        // TODO add your handling code here:
        if(jTFNumeroPesagem.getText().length()>=5){            
            buscaDadosPesagem();
        }else{
            if(jTFNumeroPesagem.getText().length()>0){
                jTFNumeroPesagem.setText("");
                JOptionPane.showMessageDialog(rootPane,"Numero da pesagem inválido","Numero Invalido",JOptionPane.ERROR_MESSAGE);                
            }
        }
    }//GEN-LAST:event_jTFNumeroPesagemFocusLost

    private void buscaDadosPesagem(){
        if( ControllerUtil.SoTemNumeros(jTFNumeroPesagem.getText())){
                if(!jTFNumeroPesagem.getText().equals(pesSaida.getCodigo())){
                    PesagemDAO dao = new PesagemDAO();                
                    pesEntrada = dao.buscaPesagemCodigo(jTFNumeroPesagem.getText());
                    if(pesEntrada!=null){
                        jLabelBobFu.setText(pesEntrada.getCodEmbalagem());
                        jLabelCodItemEntrada.setText(pesEntrada.getCodItem());
                        jLabelDescEntrada.setText(pesEntrada.getDecItem());
                        jLabelLote.setText(pesEntrada.getLote());
                        jLabelNumFiosEntrada.setText(String.valueOf(pesEntrada.getQtosFios()));
                        validarEngenharia();
                    }else{
                        jTFNumeroPesagem.setText("");
                        JOptionPane.showMessageDialog(rootPane,"Não foi possivel encotrar informações para \n"
                                + "o numero de pesagem informado. \n"
                                + "Por favor verifique e tente novamente!","Numero da pesagem inválido",JOptionPane.ERROR_MESSAGE);
                        
                    }
                }else{
                    jTFNumeroPesagem.setText("");
                    JOptionPane.showMessageDialog(rootPane,"Numero da pesagem de entrada não pode ser o mesmo da saida","Numero Invalido",JOptionPane.ERROR_MESSAGE);
                    
                }
            }else{
                jTFNumeroPesagem.setText("");
                JOptionPane.showMessageDialog(rootPane,"Numero da pesagem inválido","Numero Invalido",JOptionPane.ERROR_MESSAGE);                
            }
    }
    private void jTFNumeroPesagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNumeroPesagemKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            buscaDadosPesagem();
        }     
    }//GEN-LAST:event_jTFNumeroPesagemKeyPressed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDTrocaCarretelEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JFDTrocaCarretelEntrada dialog = new JFDTrocaCarretelEntrada(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);           
        });        
    }
    private void limparCampos() {
        jLabelBobFu.setText("");
        jLabelCodItemEntrada.setText("");
        jLabelCodItemSaida.setText("");
        jLabelDescEntrada.setText("");
        jLabelDescSaida.setText("");
        jLabelLote.setText("");
        jLabelNumFiosSaida.setText("");
        jLabelNumFiosEntrada.setText("");    
        jTFNumeroPesagem.setText("");
        jTFNumeroPesagemSaida.setText("");
        jLabelBobFuSaida.setText("");
        jLabelLoteSaida.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBobFu;
    private javax.swing.JLabel jLabelBobFuSaida;
    private javax.swing.JLabel jLabelCodItemEntrada;
    private javax.swing.JLabel jLabelCodItemSaida;
    private javax.swing.JLabel jLabelDescEntrada;
    private javax.swing.JLabel jLabelDescSaida;
    private javax.swing.JLabel jLabelLote;
    private javax.swing.JLabel jLabelLoteSaida;
    private javax.swing.JLabel jLabelNumFiosEntrada;
    private javax.swing.JLabel jLabelNumFiosSaida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFNumeroPesagem;
    private javax.swing.JTextField jTFNumeroPesagemSaida;
    private javax.swing.JTable jTableEngAlternativa;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

    public void setPesSaida(Pesagem pesSaida) {
        this.pesSaida = pesSaida;
        jLabelCodItemSaida.setText(pesSaida.getCodItem());
        jLabelDescSaida.setText(pesSaida.getDecItem());
        jLabelNumFiosSaida.setText(String.valueOf(pesSaida.getQtosFios()));
        jTFNumeroPesagemSaida.setText(pesSaida.getCodigo());
        jLabelBobFuSaida.setText(pesSaida.getCodEmbalagem());
        jLabelLoteSaida.setText(pesSaida.getLote());
    }
    
    public void buscaItensAlternativosMontagem(String codItemProducao){
        try {                    
            ControllerEngenhariaAlternativa eng = new ControllerEngenhariaAlternativa();
            prods = eng.buscaListaAlternativas(eng.buscaItemCobrePadrao(codItemProducao),codItemProducao);
            if(prods!=null){
                for(int i=0;i<prods.size();i++){
                    DefaultTableModel model = (DefaultTableModel)jTableEngAlternativa.getModel();
                    model.addRow(new Object[]{prods.get(i).item.getCodigo(),prods.get(i).item.getDescricao()} );
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }           

    private void validarEngenharia() {
        okButton.setEnabled(false);
        if(!pesEntrada.getCodItem().equals(pesSaida.getCodItem())){
            for(int i=0;i<prods.size();i++){
                if(String.valueOf(prods.get(i).item.getCodigo()).equals(pesEntrada.getCodItem())){
                    okButton.setEnabled(true);
                    return;
                }
            }
            Object[] options = { "Sim", "Não" }; 
            int i = JOptionPane.showOptionDialog(rootPane, "O item escolhido não pertence a engenharia do produto em produção. \n"
                    + "Para que possa ser utilizado será necessária uma montagem especial. \n"
                    + "Deseja realmente realizar uma montagem especial?", 
                    "Montagem especial", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, 
                    null, options, options[0]); 
            if (i == JOptionPane.YES_OPTION) {                
                JFDAutorizarSenha auth = new JFDAutorizarSenha((Frame) this.getOwner(),false); 
                auth.setCodMaquina(codMaquina);
                auth.setMetragem(metragem);
                auth.setLote(lote);
                auth.setVisible(true);                
                if(auth.getReturnStatus()==1){
                    System.out.println("Logado com sucesso!");
                    okButton.setEnabled(true);
                }else{
                    System.out.println("Falha no login");
                }                
            }else{
                jTFNumeroPesagem.setText("");
            }
        }else{
            okButton.setEnabled(true);
        }
    }
}
