/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import com.pi4j.system.SystemInfo;
import controller.Login;
import dao.DadosDefaultDAO;
import dao.MaquinaDAO;
import dao.ProgramacaoMaquinaDAO;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.DadosConexao;
import model.Maquina;
import model.ProdutoCarretel;
import model.ProdutoMaquina;
import model.ProgramacaoMaquina;
import model.Usuario;

/**
 *
 * @author renato.soares
 */
public class JFPrincipal extends javax.swing.JFrame {
    private  static String identificador;
    private static String codMaquina;
    Login login = new Login();
    Maquina maquina = new Maquina();
    MaquinaDAO maqDao =  new MaquinaDAO();
    ProdutoMaquina prodmaq = new ProdutoMaquina();
    ProdutoCarretel prodCar = new ProdutoCarretel();
    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        try {
            if(System.getProperty("os.name").equals("Linux")){
                identificador = SystemInfo.getSerial();
            }else{
                identificador = "ADMINISTRADOR";
            }
            
            System.out.println("OS. name: " + System.getProperty("os.name"));
            System.out.println("Serial: " + identificador);
            initComponents();
            Canvas logo = new Canvas();
            this.jPLogo.add(logo);
            bloquearMenu();            
            DadosDefaultDAO dados = new DadosDefaultDAO();
            codMaquina = dados.buscaCodigoMaquina(identificador);
            if(codMaquina!=null){                
                maquina = maqDao.buscarDadosMaquina(codMaquina);
            }
            
        } catch (UnsupportedOperationException | IOException | InterruptedException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpRoot = new javax.swing.JPanel();
        jpLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUser = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jbLogin = new javax.swing.JButton();
        jPLogo = new javax.swing.JPanel();
        jpProgramacao = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProgramacao = new javax.swing.JTable();
        jpParadas = new javax.swing.JPanel();
        jpProducao = new javax.swing.JPanel();
        jpConfigDefault = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfUserDafaut = new javax.swing.JTextField();
        jpfSenhaDefault = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtfDriverProducao = new javax.swing.JTextField();
        jtfServidorProducao = new javax.swing.JTextField();
        jtfUrlProducao = new javax.swing.JTextField();
        jtfBDProducao = new javax.swing.JTextField();
        jtfUsuarioProducao = new javax.swing.JTextField();
        jtfDriverTeste = new javax.swing.JTextField();
        jtfServidorTeste = new javax.swing.JTextField();
        jtfUrlTeste = new javax.swing.JTextField();
        jtfBDTeste = new javax.swing.JTextField();
        jtfUsuarioTeste = new javax.swing.JTextField();
        jbCriarArquivosDefault = new javax.swing.JButton();
        jpfSenhaProducao = new javax.swing.JPasswordField();
        jpfSenhaTeste = new javax.swing.JPasswordField();
        menuPrincipal = new javax.swing.JMenuBar();
        menuLogin = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuItemDesligar = new javax.swing.JMenuItem();
        menuProgramacao = new javax.swing.JMenu();
        jMenuItemProgramacao = new javax.swing.JMenuItem();
        menuParadas = new javax.swing.JMenu();
        jMenuItemParadas = new javax.swing.JMenuItem();
        menuProducao = new javax.swing.JMenu();
        jMenuItemProducao = new javax.swing.JMenuItem();
        menuConfiguracoes = new javax.swing.JMenu();
        jMenuConfigDefault = new javax.swing.JMenuItem();
        jMenuTrocarMaquina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Condumig");
        setExtendedState(JFPrincipal.MAXIMIZED_BOTH);
        setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        setName("framePrincipal"); // NOI18N

        jpRoot.setLayout(new java.awt.CardLayout());

        jpLogin.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Usuario: ");

        jLabel2.setText("Senha:");

        jtfUser.setText("renatoinf");

        jpfPassword.setText("vitor");

        jbLogin.setText("Login");
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });

        jPLogo.setBackground(new java.awt.Color(204, 255, 255));
        jPLogo.setName("jPLogo"); // NOI18N
        jPLogo.setLayout(new java.awt.BorderLayout(100, 100));

        javax.swing.GroupLayout jpLoginLayout = new javax.swing.GroupLayout(jpLogin);
        jpLogin.setLayout(jpLoginLayout);
        jpLoginLayout.setHorizontalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbLogin)
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfUser)
                            .addComponent(jpfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
                .addContainerGap(556, Short.MAX_VALUE))
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpLoginLayout.setVerticalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jpRoot.add(jpLogin, "jpLogin");

        jpProgramacao.setBackground(new java.awt.Color(204, 255, 255));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Acompanhamento de Programação");

        jLabel22.setText("Itens programados:");

        jTableProgramacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableProgramacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo Item", "Descrição", "Lote", "Quantidade", "Metragem prog.", "Data "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProgramacao.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTableProgramacao);

        javax.swing.GroupLayout jpProgramacaoLayout = new javax.swing.GroupLayout(jpProgramacao);
        jpProgramacao.setLayout(jpProgramacaoLayout);
        jpProgramacaoLayout.setHorizontalGroup(
            jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProgramacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpProgramacaoLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpProgramacaoLayout.createSequentialGroup()
                        .addGroup(jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jpProgramacaoLayout.setVerticalGroup(
            jpProgramacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpProgramacaoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpRoot.add(jpProgramacao, "jpProgramacao");

        jpParadas.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jpParadasLayout = new javax.swing.GroupLayout(jpParadas);
        jpParadas.setLayout(jpParadasLayout);
        jpParadasLayout.setHorizontalGroup(
            jpParadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        jpParadasLayout.setVerticalGroup(
            jpParadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );

        jpRoot.add(jpParadas, "jpParadas");

        jpProducao.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jpProducaoLayout = new javax.swing.GroupLayout(jpProducao);
        jpProducao.setLayout(jpProducaoLayout);
        jpProducaoLayout.setHorizontalGroup(
            jpProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        jpProducaoLayout.setVerticalGroup(
            jpProducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );

        jpRoot.add(jpProducao, "jpProducao");

        jpConfigDefault.setBackground(new java.awt.Color(204, 255, 255));
        jpConfigDefault.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Configurações Default");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel4.setText("Configurações usuário default");

        jLabel5.setText("Usuário:");

        jLabel6.setText("Senha:");

        jtfUserDafaut.setText("jtfUserDafaut");

        jpfSenhaDefault.setText("jPasswordField1");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel7.setText("Configurações de Banco de dados base produção:");

        jLabel8.setText("Nome do driver:");

        jLabel9.setText("Servidor:");

        jLabel10.setText("Url:");

        jLabel11.setText("Banco de dados:");

        jLabel12.setText("Usuario:");

        jLabel13.setText("Senha:");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel14.setText("Configurações de Banco de dados base teste:");

        jLabel15.setText("Nome do driver:");

        jLabel16.setText("Servidor:");

        jLabel17.setText("Url:");

        jLabel18.setText("Banco de dados:");

        jLabel19.setText("Usuário:");

        jLabel20.setText("Senha:");

        jtfDriverProducao.setText("jtfDriverProducao");

        jtfServidorProducao.setText("jtfServidorProducao");

        jtfUrlProducao.setText("jtfUrlProducao");

        jtfBDProducao.setText("jtfBDProducao");

        jtfUsuarioProducao.setText("jtfUsuarioProducao");

        jtfDriverTeste.setText("jtfDriverTeste");

        jtfServidorTeste.setText("jtfServidorTeste");

        jtfUrlTeste.setText("jtfUrlTeste");

        jtfBDTeste.setText("jtfBDTeste");

        jtfUsuarioTeste.setText("jtfUsuarioTeste");

        jbCriarArquivosDefault.setText("Guardar");
        jbCriarArquivosDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarArquivosDefaultActionPerformed(evt);
            }
        });

        jpfSenhaProducao.setText("000000000000");

        jpfSenhaTeste.setText("jPasswordField1");

        javax.swing.GroupLayout jpConfigDefaultLayout = new javax.swing.GroupLayout(jpConfigDefault);
        jpConfigDefault.setLayout(jpConfigDefaultLayout);
        jpConfigDefaultLayout.setHorizontalGroup(
            jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConfigDefaultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConfigDefaultLayout.createSequentialGroup()
                        .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpConfigDefaultLayout.createSequentialGroup()
                                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpfSenhaDefault)
                                    .addComponent(jtfUserDafaut)))
                            .addGroup(jpConfigDefaultLayout.createSequentialGroup()
                                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfServidorTeste)
                                    .addComponent(jtfUrlTeste)
                                    .addComponent(jtfBDTeste)
                                    .addComponent(jtfUsuarioTeste)
                                    .addComponent(jtfDriverTeste)))
                            .addGroup(jpConfigDefaultLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jpConfigDefaultLayout.createSequentialGroup()
                                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpConfigDefaultLayout.createSequentialGroup()
                                        .addComponent(jtfDriverProducao, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 8, Short.MAX_VALUE))
                                    .addComponent(jtfServidorProducao)
                                    .addComponent(jtfUrlProducao)
                                    .addComponent(jtfBDProducao)
                                    .addComponent(jtfUsuarioProducao)
                                    .addComponent(jpfSenhaProducao))))
                        .addContainerGap())
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addGroup(jpConfigDefaultLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpfSenhaTeste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCriarArquivosDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jpConfigDefaultLayout.setVerticalGroup(
            jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConfigDefaultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfUserDafaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jpfSenhaDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDriverProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfServidorProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfUrlProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfBDProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtfUsuarioProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jpfSenhaProducao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfDriverTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtfServidorTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtfUrlTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtfBDTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtfUsuarioTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpConfigDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jpfSenhaTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCriarArquivosDefault))
                .addGap(197, 197, 197))
        );

        jpRoot.add(jpConfigDefault, "jpConfigDefault");
        jpConfigDefault.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jpRoot, java.awt.BorderLayout.CENTER);

        menuLogin.setText("Incial");

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        menuLogin.add(jMenuItemLogin);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        menuLogin.add(jMenuItemSair);

        jMenuItemDesligar.setText("Desligar");
        jMenuItemDesligar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDesligarActionPerformed(evt);
            }
        });
        menuLogin.add(jMenuItemDesligar);

        menuPrincipal.add(menuLogin);

        menuProgramacao.setText("Programação");

        jMenuItemProgramacao.setText("Acompanhamento de programação");
        jMenuItemProgramacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProgramacaoActionPerformed(evt);
            }
        });
        menuProgramacao.add(jMenuItemProgramacao);

        menuPrincipal.add(menuProgramacao);

        menuParadas.setText("Paradas");

        jMenuItemParadas.setText("Paradas");
        jMenuItemParadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemParadasActionPerformed(evt);
            }
        });
        menuParadas.add(jMenuItemParadas);

        menuPrincipal.add(menuParadas);

        menuProducao.setText("Produção");

        jMenuItemProducao.setText("Produção");
        jMenuItemProducao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProducaoActionPerformed(evt);
            }
        });
        menuProducao.add(jMenuItemProducao);

        menuPrincipal.add(menuProducao);

        menuConfiguracoes.setText("Configurações");

        jMenuConfigDefault.setText("Default");
        jMenuConfigDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConfigDefaultActionPerformed(evt);
            }
        });
        menuConfiguracoes.add(jMenuConfigDefault);

        jMenuTrocarMaquina.setText("Trocar maquina");
        jMenuTrocarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTrocarMaquinaActionPerformed(evt);
            }
        });
        menuConfiguracoes.add(jMenuTrocarMaquina);

        menuPrincipal.add(menuConfiguracoes);

        setJMenuBar(menuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemProgramacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProgramacaoActionPerformed
        // TODO add your handling code here:       
        limparJTable(jTableProgramacao);
        buscarProgramacaoMaquina();
        CardLayout card = (CardLayout) jpRoot.getLayout();
        card.show(jpRoot,"jpProgramacao");
    }//GEN-LAST:event_jMenuItemProgramacaoActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpRoot.getLayout();
        card.show(jpRoot,"jpLogin");
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemParadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemParadasActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpRoot.getLayout();
        card.show(jpRoot,"jpParadas");
    }//GEN-LAST:event_jMenuItemParadasActionPerformed

    private void jMenuItemProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProducaoActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) jpRoot.getLayout();
        card.show(jpRoot,"jpProducao");
    }//GEN-LAST:event_jMenuItemProducaoActionPerformed

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        // TODO add your handling code here:
        
        login.setUsuario(jtfUser.getText());
        //System.out.println("usuario: " + login.getUsuario());
        login.setSenha(jpfPassword.getText());
        //System.out.println("Psw: " + login.getSenha());
        if(login.logar(login)){
            if(!login.getNome().trim().equals("")) bloquearMenu();
            habilitarMenu();
            System.out.println("Logado com " + login.getNome()
                + " e nivel de permissão: " + login.getNivel()); 
            limparTelaLogin();
            CardLayout card = (CardLayout) jpRoot.getLayout();
            card.show(jpRoot,"jpProducao");
        }else{
            JOptionPane.showMessageDialog(null, "Usuario ou Senha invalidos","Login",JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_jbLoginActionPerformed

    private void jMenuConfigDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConfigDefaultActionPerformed
        // TODO add your handling code here:
        limparCamposConfigDefault();
        DadosConexao dp =  new DadosConexao();
        DadosDefaultDAO dao = new DadosDefaultDAO();
        dp = dao.buscaDadosConexaoDefault(true);
        if(dp!=null){
            jtfBDProducao.setText(dp.getMyDatabase());
            jtfDriverProducao.setText(dp.getDriverName());
            jtfServidorProducao.setText(dp.getServerName());
            jtfUrlProducao.setText(dp.getUrl());
        }
        DadosConexao dt =  new DadosConexao();
        dt = dao.buscaDadosConexaoDefault(false);
        if(dt!=null){
            jtfBDTeste.setText(dt.getMyDatabase());
            jtfDriverTeste.setText(dt.getDriverName());
            jtfServidorTeste.setText(dt.getServerName());
            jtfUrlTeste.setText(dt.getUrl());
        }
        CardLayout card = (CardLayout) jpRoot.getLayout();
        card.show(jpRoot,"jpConfigDefault");
    }//GEN-LAST:event_jMenuConfigDefaultActionPerformed

    private void jbCriarArquivosDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarArquivosDefaultActionPerformed
        // TODO add your handling code here:
        boolean add = true;
        Usuario us = new Usuario();
        us.setUsuario(jtfUserDafaut.getText());
        us.setSenha(jpfSenhaDefault.getText());
        DadosDefaultDAO dao = new DadosDefaultDAO();
        if (!dao.ArmazenarUserDefault(us)) {
            JOptionPane.showMessageDialog(null, "Falha ao registrar dados usuario default","Usuário Default",JOptionPane.ERROR_MESSAGE);
            add = false;
        }
        DadosConexao d = new DadosConexao();
        d.setDriverName(jtfDriverProducao.getText());
        d.setMyDatabase(jtfBDProducao.getText());
        d.setPassword(jpfSenhaProducao.getText());
        d.setServerName(jtfServidorProducao.getText());
        d.setUrl(jtfUrlProducao.getText());
        d.setUserName(jtfUsuarioProducao.getText());
        if(!dao.armazenaDadosConexao(d,true)) {
            JOptionPane.showMessageDialog(null, "Falha ao registrar dados de conexão","Banco de dados Produção",JOptionPane.ERROR_MESSAGE);
            add = false;
        }
        d.setDriverName(jtfDriverTeste.getText());
        d.setMyDatabase(jtfBDTeste.getText());
        d.setPassword(jpfSenhaTeste.getText());
        d.setServerName(jtfServidorTeste.getText());
        d.setUrl(jtfUrlTeste.getText());
        d.setUserName(jtfUsuarioTeste.getText());
        if(!dao.armazenaDadosConexao(d,false)) {
            JOptionPane.showMessageDialog(null, "Falha ao registrar dados de conexão","Banco de dados Teste",JOptionPane.ERROR_MESSAGE);
            add = false;
        }
        if(add) JOptionPane.showMessageDialog(null,"Dados Registrados com sucesso");
    }//GEN-LAST:event_jbCriarArquivosDefaultActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        login.setUsuario("");
        login.setNome("");
        login.setNivel("");
        login.setSenha("");
        limparTelaLogin();
        bloquearMenu();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemDesligarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDesligarActionPerformed
        try {
            // TODO add your handling code here:
            Runtime.getRuntime().exec("shutdown -h now");
        } catch (IOException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemDesligarActionPerformed

    private void jMenuTrocarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTrocarMaquinaActionPerformed
        // TODO add your handling code here:
        JFCadastroMonitor cad = new JFCadastroMonitor();
        cad.setEdit(true);
        cad.setVisible(true);
    }//GEN-LAST:event_jMenuTrocarMaquinaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFPrincipal().setVisible(true);   
            if(codMaquina==null){
                JOptionPane.showMessageDialog(null, "Não foi encontrada uma maquina cadastrada para este sistema",
                        "Registro necessário",JOptionPane.ERROR_MESSAGE);
                new JFCadastroMonitor().setVisible(true);
            }
        });        
        /*
        String dados = "";
        String msg = "admin;admin";                 
        byte[] msgCrito = CriptoCode.encrypt(msg);
        for ( int i=0; i<msgCrito.length;i++){
            //System.out.print(new Integer(msgCrito[i])+" ");                    
            dados = dados + Byte.toString(msgCrito[i])+" ";
        }
        ManipuladorArquivo man = new ManipuladorArquivo();
        man.setArquivo(DadosDefaultDAO.getUSERDEFAULT());
        man.setDados(dados);
        man.escreverArquivo();
        
        
        this.driverName = dadosConexao[0];
                this.myDatabase = dadosConexao[1];
                this.password = dadosConexao[2];
                this.serverName = dadosConexao[3];                
                this.url = dadosConexao[4] + this.serverName + "/" + this.myDatabase ;
                this.userName = dadosConexao[5];
        //Teste de criptografia ....
        String msg = "192.168.1.74;condumigproducao;producao;Prod#153";                 
        //System.out.println(msg);         
        byte[] msgCrito = CriptoCode.encrypt(msg);    
        String dados = "";
        for ( int i=0; i<msgCrito.length;i++){
            //System.out.print(new Integer(msgCrito[i])+" ");                    
            dados = dados + Byte.toString(msgCrito[i])+" ";
        }
        
        man.setDados(dados);
        
        man.escreverArquivo();
        man.setDados("");
        */      
      
        
          
    }

    public static void setCodMaquina(String codMaquina) {
        JFPrincipal.codMaquina = codMaquina;
    }

    public static String getIdentificador() {
        return identificador;
    }
    
    private void bloquearMenu(){
        menuParadas.setEnabled(false);
        menuProducao.setEnabled(false);
        menuProgramacao.setEnabled(false );
        menuConfiguracoes.setEnabled(false);
        jMenuItemSair.setEnabled(false);
    }
    private void habilitarMenu() {    
        menuParadas.setEnabled(true);
        menuProducao.setEnabled(true);
        menuProgramacao.setEnabled(true);
        jMenuItemSair.setEnabled(true);
        if(login.getNivel().equals("0")){
            menuConfiguracoes.setEnabled(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuConfigDefault;
    private javax.swing.JMenuItem jMenuItemDesligar;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemParadas;
    private javax.swing.JMenuItem jMenuItemProducao;
    private javax.swing.JMenuItem jMenuItemProgramacao;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuTrocarMaquina;
    private javax.swing.JPanel jPLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTableProgramacao;
    private javax.swing.JButton jbCriarArquivosDefault;
    private javax.swing.JButton jbLogin;
    private javax.swing.JPanel jpConfigDefault;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JPanel jpParadas;
    private javax.swing.JPanel jpProducao;
    private javax.swing.JPanel jpProgramacao;
    private javax.swing.JPanel jpRoot;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPasswordField jpfSenhaDefault;
    private javax.swing.JPasswordField jpfSenhaProducao;
    private javax.swing.JPasswordField jpfSenhaTeste;
    private javax.swing.JTextField jtfBDProducao;
    private javax.swing.JTextField jtfBDTeste;
    private javax.swing.JTextField jtfDriverProducao;
    private javax.swing.JTextField jtfDriverTeste;
    private javax.swing.JTextField jtfServidorProducao;
    private javax.swing.JTextField jtfServidorTeste;
    private javax.swing.JTextField jtfUrlProducao;
    private javax.swing.JTextField jtfUrlTeste;
    private javax.swing.JTextField jtfUser;
    private javax.swing.JTextField jtfUserDafaut;
    private javax.swing.JTextField jtfUsuarioProducao;
    private javax.swing.JTextField jtfUsuarioTeste;
    private javax.swing.JMenu menuConfiguracoes;
    private javax.swing.JMenu menuLogin;
    private javax.swing.JMenu menuParadas;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuProducao;
    private javax.swing.JMenu menuProgramacao;
    // End of variables declaration//GEN-END:variables

    private void limparCamposConfigDefault() {
        jtfUserDafaut.setText("");
        jpfSenhaDefault.setText("");
        jtfUsuarioProducao.setText("");
        jpfSenhaProducao.setText("");
        jtfUsuarioTeste.setText("");
        jpfSenhaTeste.setText("");
    }
    
    private void limparTelaLogin(){
        jtfUser.setText("");
        jpfPassword.setText("");
    }
   
    private void limparJTable(JTable tabela ){
        DefaultTableModel tblRemove = (DefaultTableModel)tabela.getModel();
        while(tblRemove.getRowCount()>0){                        
            tblRemove.removeRow(0);                 
        }
    }
        
    private void buscarProgramacaoMaquina() {   
        DefaultTableModel modelo = (DefaultTableModel)jTableProgramacao.getModel();
        ProgramacaoMaquinaDAO prog =  new ProgramacaoMaquinaDAO();
        List<ProgramacaoMaquina> lista =  new ArrayList<ProgramacaoMaquina>();
        lista = prog.buscaProgramacaoMaquina(codMaquina);
        for(int i=0;i<lista.size();i++){
            modelo.addRow(new Object[]{lista.get(i).getProduto().getCodigo(),
                lista.get(i).getProduto().getDescricao(),lista.get(i).getLoteproducao(),
                lista.get(i).getQuantidadeProgramada(),lista.get(i).getMetragemProgramada(),lista.get(i).getDataProgramada()});
        }
    }
}                                 
